server {
    listen 80;
    server_name app1.local;
    return 301 https://$host$request_uri; # принудительное перенаправление
}

server {
    listen 443 ssl;
    server_name app1.local;
    ssl_certificate /etc/nginx/ssl/nginx.crt; # использование сертификата
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
        proxy_pass http://app1:5000;
    }

    location /files/ {
        alias /usr/share/nginx/html/;
    }
}
