# исправление первого: используем конкретные легкие образы
FROM python:3.9-alpine

# исправление второго: объединяем ран команды и чистим кэш, это снижает количество слоев и нагруженность
RUN apk add --no-cache curl \
    && adduser -D appuser # исправление третьего: добавили юзера не рута

USER appuser
WORKDIR /app
COPY app.py .

CMD ["python", "app.py"]
