services:
  db:
    # плохая практика 1: использование тега лейтест, это лишает нас надежности файла, так как при обновлении образа могут появиться ошибки
    image: postgres:latest
    # плохая практика 2: хардкод ключей, паролей. это могут украсть, например программами для поиска секретов в репозиториях
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    # плохая практика 3: нет директории на самом компьютере, данные хранятся прямо в контейнере, и при удалении контейнера данные исчезнут вместе с ним
  web:
    image: nginx:latest
    ports:
      - "8080:80"
