name: bad-pipeline

on:
  push:
  pull_request:

env:
  # хранение секретов в открытом виде, что может привести к краде данных
  DOCKER_PASS: super_secret_password

jobs:
  build:
    # отсутствие жесткой фиксации версии ос может сломать сборку при обновлениях
    runs-on: ubuntu-latest
    steps:
      # использование устаревшей версии базового экшена
      - uses: actions/checkout@v2

      - name: test script
        run: |
          chmod +x script.sh
          # прямая передача переменной в команду ведет к риску инъекций
          ./script.sh --password=${DOCKER_PASS}

      # выполнение всех действий в одном шаге усложняет отладку и логирование
      - name: build and push
        run: |
          docker build -t bad-app .
          echo "${DOCKER_PASS}" | docker login -u "admin" --password-stdin
          docker push bad-app
