name: vault-pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fetch-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # использование специализированного экшена для интеграции с vault
      - name: import secrets
        uses: hashicorp/vault-action@v2.8.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/ci/docker username | DOCKER_USER ;
            secret/ci/docker password | DOCKER_PASS

      - name: verify
        run: |
          echo "secrets loaded securely"
          echo "username is ${#DOCKER_USER} characters long"
